"""Delete unique for movie title

Revision ID: 510b81d073a5
Revises: 7ef246f163e6
Create Date: 2025-05-15 21:48:30.112750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510b81d073a5'
down_revision: Union[str, None] = '7ef246f163e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_title', table_name='movies')
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.create_index('ix_movies_title', 'movies', ['title'], unique=True)
    # ### end Alembic commands ###
