"""Add preferences, image_url, and purchase history

Revision ID: 5ba12545e5ba
Revises: 582478770e22
Create Date: 2025-05-12 15:34:17.792502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba12545e5ba'
down_revision: Union[str, None] = '582478770e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_history_id'), 'purchase_history', ['id'], unique=False)
    op.add_column('movies', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('movies', 'image_url')
    op.drop_index(op.f('ix_purchase_history_id'), table_name='purchase_history')
    op.drop_table('purchase_history')
    # ### end Alembic commands ###
