version: '3.8'

services:
    api:
        build: .
        ports:
            - '8000:8000'
        environment:
            - DATABASE_URL=postgresql://postgres:03102004@db/movieticketdb
            - PINECONE_API_KEY=${PINECONE_API_KEY}
            - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
            - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
            - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
            - HUGGINGFACE_MODEL=${HUGGINGFACE_MODEL}
            - VNPAY_TMN_CODE=${VNPAY_TMN_CODE}
            - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
        depends_on:
            - db
        volumes:
            - .:/app
        restart: always

    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=03102004
            - POSTGRES_DB=movieticketdb
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

volumes:
    postgres_data:
